// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  roomId: __t.u64().name("room_id"),
  name: __t.string(),
  kind: __t.string(),
  homeLat: __t.f64().name("home_lat"),
  homeLng: __t.f64().name("home_lng"),
  paramA: __t.f64().name("param_a"),
  spawnedAt: __t.timestamp().name("spawned_at"),
});
