// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  roomId: __t.u64().name("room_id"),
  lat: __t.f64(),
  lng: __t.f64(),
  hasFix: __t.bool().name("has_fix"),
  lastSeen: __t.timestamp().name("last_seen"),
  status: __t.string(),
});
