// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CreateHuddleReducer from "../create_huddle_reducer";
import EndHuddleReducer from "../end_huddle_reducer";
import JoinHuddleReducer from "../join_huddle_reducer";
import LeaveHuddleReducer from "../leave_huddle_reducer";
import SetProfileReducer from "../set_profile_reducer";

export type CreateHuddleParams = __Infer<typeof CreateHuddleReducer>;
export type EndHuddleParams = __Infer<typeof EndHuddleReducer>;
export type JoinHuddleParams = __Infer<typeof JoinHuddleReducer>;
export type LeaveHuddleParams = __Infer<typeof LeaveHuddleReducer>;
export type SetProfileParams = __Infer<typeof SetProfileReducer>;

