// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  roomId: __t.u64().name("room_id"),
  lat: __t.f64(),
  lng: __t.f64(),
  status: __t.string(),
  candidateStartedAt: __t.timestamp().name("candidate_started_at"),
  activatedAt: __t.option(__t.timestamp()).name("activated_at"),
  coolingStartedAt: __t.option(__t.timestamp()).name("cooling_started_at"),
  endedAt: __t.option(__t.timestamp()).name("ended_at"),
  warmth: __t.f64(),
  memberCount: __t.u32().name("member_count"),
  lastWarmthTickAt: __t.timestamp().name("last_warmth_tick_at"),
});
